// Auto-generated. Edit the source MDs and run npm run build:knowledge.
// DO NOT edit this file by hand — changes will be overwritten on next build.
//
// Sources:


// ─── Types ───────────────────────────────────────────────────────────────────

export interface Instruction {
  instruction: string;
  questions: string[];
}

export interface SqlPair {
  question: string;
  sql: string;
}

export interface TableSchema {
  table: string;
  alias: string;
  description: string;
  keyColumns: string[];
}

export interface Relationship {
  from: string;
  fromColumn: string;
  to: string;
  toColumn: string;
  type: string;
}

// ─── Instructions (business rules the LLM must follow) ───────────────────────

export const INSTRUCTIONS: Instruction[] = [

];

// ─── SQL Pairs (example question -> SQL for RAG) ─────────────────────────────

export const SQL_PAIRS: SqlPair[] = [

];

// ─── PostgreSQL schema reference (ps_* tables, key columns) ──────────────────

export const SCHEMA: TableSchema[] = [

];

// ─── Relationships ───────────────────────────────────────────────────────────

export const RELATIONSHIPS: Relationship[] = [

];
