// @vitest-environment node
/**
 * Python↔TypeScript grammar parity (issue #491, EC-4).
 *
 * Consumes `etl/tests/fixtures/url-grammar-cases.json` — GENERATED by the Python
 * side from the connectors' own grammars (etl/tests/grammar_contract.py) — and
 * asserts that the generic `inferParams` produces the SAME result the Python
 * `SearchUrlGrammar.parse` produced for every case. Parity is therefore
 * enforced by shared data, not by two implementations agreeing by discipline.
 * If a grammar changes and the fixture is regenerated, both suites move
 * together; if only one moves, this test (or the pytest golden check) fails.
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, it, expect } from "vitest";
import { inferParams, buildUrl, parseGrammar, rejection, type SearchUrlGrammar } from "../parse";

interface FixtureCase {
  url: string;
  expected: Record<string, string> | null;
  /** Reject-reason key (issue #493), or null/absent for a non-rejected URL. */
  reject?: string | null;
}
interface FixtureConnector {
  connector: string;
  grammar: { build_template: string; parse_pattern: string; params: Record<string, unknown> };
  cases: FixtureCase[];
}
interface Fixture {
  connectors: FixtureConnector[];
}

const FIXTURE_PATH = path.resolve(
  __dirname,
  "../../../../etl/tests/fixtures/url-grammar-cases.json",
);

function loadFixture(): Fixture {
  return JSON.parse(readFileSync(FIXTURE_PATH, "utf-8")) as Fixture;
}

describe("URL grammar parity with Python (fixture-driven)", () => {
  const fixture = loadFixture();

  it("has at least one connector with cases", () => {
    expect(fixture.connectors.length).toBeGreaterThan(0);
    for (const c of fixture.connectors) expect(c.cases.length).toBeGreaterThan(0);
  });

  for (const c of fixture.connectors) {
    describe(`connector: ${c.connector}`, () => {
      const grammar = parseGrammar(c.grammar) as SearchUrlGrammar;

      it("parses into a valid grammar", () => {
        expect(grammar).not.toBeNull();
        expect(grammar.buildTemplate).toBe(c.grammar.build_template);
        expect(grammar.parsePattern).toBe(c.grammar.parse_pattern);
      });

      for (const [i, testCase] of c.cases.entries()) {
        const rej = testCase.reject ?? null;
        it(`case ${i}: ${testCase.url} → ${testCase.expected === null ? "null" : JSON.stringify(testCase.expected)}`, () => {
          const got = inferParams(grammar, testCase.url);
          expect(got).toEqual(testCase.expected);
        });

        // Rejection parity (issue #493): the browser and Python agree on which
        // URLs are robots-forbidden reasoned blocks vs plain no-matches.
        it(`case ${i}: rejection ${testCase.url} → ${rej === null ? "null" : rej}`, () => {
          expect(rejection(grammar, testCase.url)).toBe(rej);
        });

        // Only round-trip a genuinely usable URL: not a no-match, and not a
        // reasoned rejection (a bare-geography URL parses but must never be
        // rebuilt/pinned).
        if (testCase.expected !== null && rej === null) {
          it(`case ${i}: buildUrl round-trips ${testCase.url}`, () => {
            // build(params) reconstructs the exact URL the grammar parsed.
            expect(buildUrl(grammar, testCase.expected as Record<string, string>)).toBe(
              testCase.url,
            );
          });
        }
      }
    });
  }
});

describe("parseGrammar defensive parsing", () => {
  it("returns null for non-object / missing fields", () => {
    expect(parseGrammar(null)).toBeNull();
    expect(parseGrammar(42)).toBeNull();
    expect(parseGrammar({})).toBeNull();
    expect(parseGrammar({ build_template: "x" })).toBeNull();
  });

  it("tolerates a missing/odd params object", () => {
    const g = parseGrammar({ build_template: "https://x/{a}/", parse_pattern: "^(?<a>.+)$" });
    expect(g).not.toBeNull();
    expect(g!.params).toEqual({});
  });
});

describe("inferParams", () => {
  const grammar: SearchUrlGrammar = {
    buildTemplate: "https://www.pisos.com/venta/pisos-{geography}/",
    parsePattern: "^https?://(?:www\\.)?pisos\\.com/venta/pisos-(?<geography>[^/]+)/?$",
    params: { geography: { label: "Municipio", source: "profile" } },
    rejectReasons: [],
  };

  it("returns null for a URL that doesn't match", () => {
    expect(inferParams(grammar, "https://www.habitaclia.com/x.htm")).toBeNull();
  });

  it("returns the named groups for a matching URL", () => {
    expect(inferParams(grammar, "https://www.pisos.com/venta/pisos-madrid/")).toEqual({
      geography: "madrid",
    });
  });

  it("returns null for a malformed pattern instead of throwing", () => {
    const bad: SearchUrlGrammar = {
      buildTemplate: "",
      parsePattern: "(?<a>[",
      params: {},
      rejectReasons: [],
    };
    expect(inferParams(bad, "anything")).toBeNull();
  });
});

describe("rejection (issue #493)", () => {
  const grammar: SearchUrlGrammar = {
    buildTemplate:
      "https://www.fotocasa.es/es/comprar/viviendas/{geography}/{zone}/{rooms_segment}l",
    parsePattern:
      "^https?://(?:www\\.)?fotocasa\\.es/es/comprar/viviendas/(?<geography>[^/]+)/(?<zone>[^/]+)/(?<rooms_segment>(?:[0-9]+-habitaciones/)?)l$",
    params: {},
    rejectReasons: [
      { pattern: "^https?://(?:www\\.)?fotocasa\\.es/[^?]*\\?", reason: "robots-query-params" },
      {
        pattern:
          "^https?://(?:www\\.)?fotocasa\\.es/es/comprar/viviendas/(?:barcelona|madrid|valencia)/",
        reason: "robots-bare-geography",
      },
    ],
  };

  it("rejects a query string with the robots-query-params reason", () => {
    expect(
      rejection(
        grammar,
        "https://www.fotocasa.es/es/comprar/viviendas/madrid-capital/todas-las-zonas/l?minPrice=100000",
      ),
    ).toBe("robots-query-params");
  });

  it("rejects a bare city-name slug even though it parses (precedence)", () => {
    const url = "https://www.fotocasa.es/es/comprar/viviendas/madrid/todas-las-zonas/l";
    expect(inferParams(grammar, url)).not.toBeNull();
    expect(rejection(grammar, url)).toBe("robots-bare-geography");
  });

  it("does not reject a valid URL", () => {
    expect(
      rejection(
        grammar,
        "https://www.fotocasa.es/es/comprar/viviendas/madrid-capital/todas-las-zonas/2-habitaciones/l",
      ),
    ).toBeNull();
  });

  it("returns null when the grammar declares no reject reasons", () => {
    const g: SearchUrlGrammar = { ...grammar, rejectReasons: [] };
    expect(rejection(g, "https://www.fotocasa.es/x?y=1")).toBeNull();
  });
});
