"""Slug/XML parsing for the Cimenta2 sitemap-index connector (issue #136).

Everything here reads the **public, robots-allowed sitemap** and nothing
else. There is deliberately no detail-page parsing in this module, and
there must never be one added: see `cimenta2.py`'s module docstring and
[D-033](../../docs/decisions/D-033-cimenta2-not-viable-guest-api-overexposure.md)
for why the only channel that yields property detail on this site is
off-limits.

The two extraction points below both use `extraction.first_present`, and
for the same non-obvious reason rather than as boilerplate: this connector
declares `discovers_full_inventory = True`, so a parse that silently
matches *nothing* is not "sparse data", it is
`etl.orchestrator._reconcile_missed_discoveries` concluding that all 3,917
Cajamar assets were withdrawn at once. A single strict regex is a
single point of failure with a catastrophic, silent failure mode; a
fallback chain plus the hard "recognised nothing -> raise" guard in
`cimenta2.discover()` turns that into either a recovery or a loud error.
"""

from __future__ import annotations

import json
import re
import unicodedata
from decimal import Decimal, InvalidOperation
from urllib.parse import unquote, urlsplit

from etl.connectors.extraction import first_present

# Live-verified 2026-08-04 against the complete sitemap: all 3,917 asset
# URLs match this exact shape, 3,917 distinct 18-character Salesforce record
# ids paired 1:1 with 3,917 distinct reference codes (zero duplicates on
# either side). The id length is accepted as 15-18 because Salesforce ids
# are natively 15 characters case-sensitive and 18 characters
# case-insensitive; the sitemap publishes the 18-character form today, and
# pinning the parser to 18 alone would break on a generator that switched to
# the equally valid 15-character form.
_ASSET_PATH_RE = re.compile(
    r"^/inmuebles/s/ga-activo/(?P<record_id>[A-Za-z0-9]{15,18})/(?P<reference>[^/]+)$"
)

# Deliberately tolerant sibling of the above, used only as a fallback: same
# path prefix, but indifferent to a trailing slash, a query string, a
# fragment, or extra path noise after the reference. See
# `reference_code_from_url` for why that laxness is wanted in second
# position and not in first.
_ASSET_PATH_LOOSE_RE = re.compile(
    r"/inmuebles/s/ga-activo/(?P<record_id>[A-Za-z0-9]{15,18})/(?P<reference>[^/?#]+)"
)

_LOC_RE = re.compile(r"<loc>\s*([^<\s]+)\s*</loc>", re.IGNORECASE)

# The asset object's child sitemap, as named in the live sitemap index.
# `-1` is the numbered partition; `-weekly` is a second entry the index also
# publishes. Live-verified 2026-08-04: the two are not a full set and a
# delta -- they returned byte-identical 556,639-byte bodies with the same
# 3,917 URLs, so either one alone is the complete asset catalogue. That is
# what makes the weekly variant a safe fallback rather than a partial one.
_ASSET_SITEMAP_TOKEN = "sitemap-ga_activo__c-1.xml"
_ASSET_SITEMAP_WEEKLY_TOKEN = "sitemap-ga_activo__c-weekly.xml"


def iter_locs(xml: str) -> list[str]:
    """Every `<loc>` value in a sitemap or sitemap index, in document order.

    A regex rather than an XML parser, matching the house pattern
    (`vivantial.py`, `servihabitat.py`): these documents are machine-
    generated by Salesforce and the connector wants a *lenient* read, since
    the realistic failure mode is an HTML error page served with a 200,
    which a strict parser would turn into an XML exception rather than the
    "zero entries" signal `cimenta2.discover()` checks for explicitly.
    """
    return _LOC_RE.findall(xml)


def record_id_from_url(url: str) -> str | None:
    """The 18-character Salesforce record id, used as this connector's
    `external_id`.

    The record id is the external_id rather than the human reference code
    because it is what the URL is *addressed* by: the reference code is a
    Cajamar-side business identifier that a servicer is free to re-issue,
    while the record id is the primary key of the row the page renders.
    Using the reference code would also silently collapse two assets the day
    Cajamar reuses one, and `listing` is keyed `UNIQUE (source,
    external_id)`.
    """
    path = urlsplit(url).path
    strict = _ASSET_PATH_RE.match(path)
    if strict is not None:
        return strict.group("record_id")
    loose = _ASSET_PATH_LOOSE_RE.search(path)
    if loose is not None:
        return loose.group("record_id")
    return None


def reference_code_from_url(url: str) -> str | None:
    """The per-property reference code Cajamar puts in the URL slug (#72).

    Two getters, in decreasing strictness:

    1. The exact shape every one of the 3,917 live asset URLs has today.
    2. A tolerant re-read that ignores a trailing slash, a query string, a
       fragment, or trailing path noise.

    The second is not defensive boilerplate. This connector's *only*
    per-property datum is this code, and a sitemap generator appending
    `?utm_source=...` or a trailing `/` is a cosmetic change a site can make
    at any time without notice. With a strict-only parse that change would
    make every URL unrecognisable at once, which for a
    `discovers_full_inventory = True` connector reads as a total withdrawal
    of the catalogue rather than as the parsing regression it is.

    Percent-decoded because the sibling `inv-expediente` sitemap does emit
    percent-encoded UTF-8 in its slugs (`...canj%C3%A1yar-almer%C3%ADa`);
    no live asset reference needs decoding today, but decoding an
    already-plain ASCII code is a no-op, and not decoding a future accented
    one would store a mangled value.
    """
    path = urlsplit(url).path

    def strict() -> str | None:
        match = _ASSET_PATH_RE.match(path)
        return unquote(match.group("reference")) if match else None

    def loose() -> str | None:
        match = _ASSET_PATH_LOOSE_RE.search(path)
        return unquote(match.group("reference")) if match else None

    code = first_present(strict, loose, field="cimenta2.reference_code")
    if code is None:
        return None
    code = code.strip()
    return code or None


def parse_asset_url(url: str) -> tuple[str, str] | None:
    """`(record_id, reference_code)` for an asset URL, or None if it is not one.

    Returning None (rather than raising) for a non-asset URL is what lets
    `discover()` walk a mixed sitemap and simply ignore anything that is not
    a `ga-activo` entry. The "we recognised *nothing*" case is the one that
    raises, and that check lives in `discover()` where the count is known.
    """
    record_id = record_id_from_url(url)
    if record_id is None:
        return None
    reference = reference_code_from_url(url)
    if reference is None or reference == record_id:
        # A slug-less URL (`/ga-activo/<id>`) would otherwise hand back the
        # record id as though it were a Cajamar reference code, seeding the
        # dedup engine's reference_code signal with a value that is not a
        # reference code at all. No such URL exists in the live sitemap;
        # this is the honest handling if one ever appears.
        return None
    return record_id, reference


# ===========================================================================
# Detail fetch — Salesforce Aura getRecord (issue #136, D-035)
# ===========================================================================
#
# The connector fetches per-property detail only when a detail endpoint is
# injected via config (never committed — see D-035). The mechanics below are
# generic and non-secret: the `getRecord` action descriptor is a STOCK
# Salesforce controller shared by every Experience Cloud community, and the
# fwuid + app-version marker are scraped fresh from the site's own public
# shell HTML on each run so a stale build id is never carried. The only
# site-specific secret — the endpoint URL — lives in config, not here.

# Standard record-detail controller action (not a custom Apex method). Safe to
# keep in code precisely because it is identical across all communities.
GETRECORD_DESCRIPTOR = (
    "serviceComponent://ui.force.components.controllers.detail."
    "DetailController/ACTION$getRecord"
)

# fwuid and the app version marker both appear plainly in the shell HTML, no JS
# execution required (regexes per the request-mechanics reference).
_FWUID_RE = re.compile(r"/auraFW/javascript/([^/]+)/aura_prod\.js")
_APP_MARKER_RE = re.compile(r'communityApp"?\s*:\s*"?([0-9]+_[A-Za-z0-9_-]+)"')

# Public property fields the site itself renders — the ONLY keys ever read off
# a fetched record. This whitelist is the structural guarantee behind D-035's
# "owner-contact fields are never stored": those keys (and every other
# unlisted internal field) are simply absent here, so no code path can copy
# them into a canonical row or raw_extra.
PUBLIC_FIELD_KEYS = (
    "Name",
    "GA_Direccion__c",
    "GA_Poblacion__c",
    "GA_Provincia__c",
    "GA_Provincia__c__f",  # province label variant (coded value + label)
    "GA_Geolocalizacion__Latitude__s",
    "GA_Geolocalizacion__Longitude__s",
    "GA_SuperficieCons__c",
    "GA_SuperficieUtil__c",
    "GA_NumeroHabitaciones__c",
    "GA_NumBanos__c",
    "GA_ReferenciaCatastral__c",
    "GA_PVPVigentePVPVentaReport__c",
    "GA_PrecioPermanente__c",
    "GA_TipologiaActivoCategoria__c",
    "GA_TipologiaActivoSubCategoria__c",
    "GA_CEE__c",
    "GA_EnlaceWeb__c",
)

# Bank-internal commercial fields — kept in raw_extra ONLY when the operator
# opts in via CIMENTA2_INCLUDE_INTERNAL (default off, D-035).
INTERNAL_COMMERCIAL_KEYS = (
    "GA_CosteDeAdquisicion__c",  # acquisition cost
    "GA_ValorDeTasacion__c",  # appraisal value
)

# Owner-contact fields that must NEVER be read or stored (D-035). No code path
# references this tuple — it exists purely as the documented negative
# guarantee and as an assertion target for the test suite.
OWNER_CONTACT_KEYS = (
    "GA_UNI__c",
    "GA_DatosComPropietarios_NifPresuntoClien__c",
    "GA_DatosComPropietarios_Telefono__c",
    "GA_DatosComPropietarios_Iban__c",
    "GA_DatosComPropietarios_Poblacion__c",
)


def scrape_framework_ids(shell_html: str) -> tuple[str, str] | None:
    """Pull the current `(fwuid, app_version_marker)` out of the shell HTML.

    Returns None when either cannot be found — the site structure may have
    changed, or guest access may have been withdrawn. The connector treats
    None as a loud, circuit-breaker-countable failure rather than retrying.
    """
    m_fwuid = _FWUID_RE.search(shell_html)
    decoded = unquote(shell_html)
    m_marker = _APP_MARKER_RE.search(decoded)
    if not m_fwuid or not m_marker:
        return None
    return m_fwuid.group(1), m_marker.group(1)


def aura_request_form(record_id: str, fwuid: str, marker: str) -> dict[str, str]:
    """The form-encoded body for one guest `getRecord` call.

    `aura.token` is the literal string ``null`` — guest Aura traffic carries no
    session token. `layoutType=FULL` requests the record's full field set; the
    connector then reads only the whitelisted public keys from it.
    """
    context = {
        "mode": "PROD",
        "fwuid": fwuid,
        "app": "siteforce:communityApp",
        "loaded": {"APPLICATION@markup://siteforce:communityApp": marker},
        "dn": [],
        "globals": {},
        "uad": False,
    }
    message = {
        "actions": [
            {
                "id": "1;a",
                "descriptor": GETRECORD_DESCRIPTOR,
                "callingDescriptor": "UNKNOWN",
                "params": {
                    "recordId": record_id,
                    "record": None,
                    "inContextOfComponent": "",
                    "mode": "VIEW",
                    "layoutType": "FULL",
                    "defaultFieldValues": None,
                    "navigationLocation": "LIST_VIEW_ROW",
                },
            }
        ]
    }
    return {
        "message": json.dumps(message),
        "aura.context": json.dumps(context),
        "aura.token": "null",
        "aura.pageURI": f"/inmuebles/s/ga-activo/{record_id}/",
    }


def response_is_expired(raw_text: str) -> bool:
    """A stale fwuid/marker yields an `aura:expiredFrameworkUid` event rather
    than a normal action result — refresh the context once and retry."""
    return "expiredFrameworkUid" in raw_text or "clientOutOfSync" in raw_text


def record_from_response(raw_text: str) -> dict:
    """The flat record dict from one getRecord response.

    Raises ``ValueError`` on a malformed or non-SUCCESS response — the
    connector maps that to ``ConnectorError`` so the run stops cleanly through
    the circuit breaker instead of looping. An empty ``{}`` (SUCCESS but no
    record payload) is a per-asset skip, not a stop, so it is returned rather
    than raised.
    """
    data = json.loads(raw_text)  # JSONDecodeError is a ValueError subclass
    actions = data.get("actions") or []
    if not actions:
        raise ValueError("aura response carried no actions")
    action = actions[0]
    state = action.get("state")
    if state != "SUCCESS":
        raise ValueError(f"aura action state was {state!r}, not SUCCESS")
    return_value = action.get("returnValue") or {}
    record = return_value.get("record") or {}
    return record if isinstance(record, dict) else {}


def project_public_fields(record: dict) -> dict:
    """Copy ONLY the whitelisted public keys out of a fetched record.

    Owner-contact PII and unlisted internal fields are dropped here, before the
    value ever leaves the fetch step — the strongest place to enforce D-035.
    """
    return {key: record[key] for key in PUBLIC_FIELD_KEYS if key in record}


def project_internal_fields(record: dict) -> dict:
    """Copy the two bank-internal commercial keys, if present. Called only when
    the operator has opted into CIMENTA2_INCLUDE_INTERNAL."""
    return {
        key: _clean(record[key]) for key in INTERNAL_COMMERCIAL_KEYS if key in record
    }


# --------------------------------------------------------------------------- #
# Value coercion (pure; used by the connector's normalize())
# --------------------------------------------------------------------------- #


def _clean(value):
    """Return a stripped scalar, or None for empty/absent/nested values.

    Salesforce compound/lookup fields arrive as ``{displayValue, value}``
    dicts — take the display value, never a nested object.
    """
    if value is None:
        return None
    if isinstance(value, dict):
        value = value.get("displayValue") or value.get("value")
        if isinstance(value, dict):
            return None
    if isinstance(value, str):
        value = value.strip()
        return value or None
    return value


def _dec(value) -> Decimal | None:
    value = _clean(value)
    if value is None:
        return None
    if isinstance(value, str):
        text = value.replace("€", "").strip()
        # Tolerate Spanish-formatted numbers ("1.234,56") just in case.
        if "," in text and "." in text:
            text = text.replace(".", "").replace(",", ".")
        elif "," in text:
            text = text.replace(",", ".")
        text = re.sub(r"[^0-9.\-]", "", text)
        if not text:
            return None
        value = text
    try:
        return Decimal(str(value))
    except (InvalidOperation, ValueError):
        return None


def _int(value) -> int | None:
    decimal_value = _dec(value)
    return int(decimal_value) if decimal_value is not None else None


def _norm(text: str) -> str:
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    return text.upper().strip()


# property.property_type CHECK enum: piso|chalet|atico|local|nave|garaje|terreno|edificio
def map_property_type(category, subcategory) -> str | None:
    """Map Cimenta2 tipología onto the property_type enum, or None.

    Conservative: anything unrecognised maps to None (the column is nullable),
    so an unexpected label never aborts an insert nor asserts false precision.
    """
    blob = (
        f"{_norm(str(_clean(category) or ''))} {_norm(str(_clean(subcategory) or ''))}"
    )

    def has(*words: str) -> bool:
        return any(word in blob for word in words)

    if has("GARAJE", "PARKING", "APARCAMIENTO", "PLAZA DE GARAJE"):
        return "garaje"
    if has("NAVE"):
        return "nave"
    if has("EDIFICIO"):
        return "edificio"
    if has("SUELO", "TERRENO", "PARCELA", "SOLAR", "FINCA", "RUSTIC"):
        return "terreno"
    if has("OFICINA", "LOCAL", "COMERCIAL", "TRASTERO"):
        return "local"
    if has("ATICO"):
        return "atico"
    if has("CHALET", "UNIFAMILIAR", "ADOSAD", "PAREAD", "VILLA"):
        return "chalet"
    if has("VIVIENDA", "PISO", "APARTAMENTO", "DUPLEX", "ESTUDIO"):
        return "piso"
    return None


def canonical_property_fields(fields: dict) -> dict:
    """Coerce the whitelisted public `fields` into canonical-row values.

    Reads only keys already projected by `project_public_fields`, so this stays
    within the D-035 whitelist. Returns the exact set the connector's
    normalize() needs; a missing/unparseable field becomes None honestly.
    """
    return {
        "reference_code": _clean(fields.get("Name")),
        "current_price": _dec(fields.get("GA_PVPVigentePVPVentaReport__c"))
        or _dec(fields.get("GA_PrecioPermanente__c")),
        "address": _clean(fields.get("GA_Direccion__c")),
        "city": _clean(fields.get("GA_Poblacion__c")),
        "province": _clean(fields.get("GA_Provincia__c__f"))
        or _clean(fields.get("GA_Provincia__c")),
        "lat": _dec(fields.get("GA_Geolocalizacion__Latitude__s")),
        "lon": _dec(fields.get("GA_Geolocalizacion__Longitude__s")),
        "m2_built": _dec(fields.get("GA_SuperficieCons__c")),
        "m2_useful": _dec(fields.get("GA_SuperficieUtil__c")),
        "rooms": _int(fields.get("GA_NumeroHabitaciones__c")),
        "bathrooms": _int(fields.get("GA_NumBanos__c")),
        "cadastral_ref": _clean(fields.get("GA_ReferenciaCatastral__c")),
        "property_type": map_property_type(
            fields.get("GA_TipologiaActivoCategoria__c"),
            fields.get("GA_TipologiaActivoSubCategoria__c"),
        ),
        "energy_rating": _clean(fields.get("GA_CEE__c")),
        "web_url": _clean(fields.get("GA_EnlaceWeb__c")),
    }


def asset_sitemap_url(index_xml: str, *, base_url: str, default_url: str) -> str | None:
    """Pick the asset child-sitemap URL out of the sitemap index.

    Three getters, and the middle one is the interesting one:

    1. The numbered partition (`...ga_activo__c-1.xml`) the index advertises.
    2. The `-weekly` variant. Safe as a fallback specifically because it was
       live-verified to be the *same complete set*, not a recent-changes
       delta -- see `_ASSET_SITEMAP_WEEKLY_TOKEN`. A guessed-at "weekly
       means delta" would have been a quietly partial sweep, which is the
       one thing a full-inventory connector must not do.
    3. The well-known URL, constructed directly. Covers an index that
       returns successfully but lists nothing recognisable.

    Returns None only when the index itself was unreadable enough that even
    `default_url` should not be trusted -- the caller decides what to do.
    """
    locs = iter_locs(index_xml)

    def numbered() -> str | None:
        return next((loc for loc in locs if _ASSET_SITEMAP_TOKEN in loc), None)

    def weekly() -> str | None:
        return next((loc for loc in locs if _ASSET_SITEMAP_WEEKLY_TOKEN in loc), None)

    def well_known() -> str | None:
        return default_url

    url = first_present(numbered, weekly, well_known, field="cimenta2.asset_sitemap")
    if url is None:
        return None
    if url.startswith("/"):
        return f"{base_url.rstrip('/')}{url}"
    return url
