"""Slug/XML parsing for the Cimenta2 sitemap-index connector (issue #136).

Everything here reads the **public, robots-allowed sitemap** and nothing
else. There is deliberately no detail-page parsing in this module, and
there must never be one added: see `cimenta2.py`'s module docstring and
[D-033](../../docs/decisions/D-033-cimenta2-not-viable-guest-api-overexposure.md)
for why the only channel that yields property detail on this site is
off-limits.

The two extraction points below both use `extraction.first_present`, and
for the same non-obvious reason rather than as boilerplate: this connector
declares `discovers_full_inventory = True`, so a parse that silently
matches *nothing* is not "sparse data", it is
`etl.orchestrator._reconcile_missed_discoveries` concluding that all 3,917
Cajamar assets were withdrawn at once. A single strict regex is a
single point of failure with a catastrophic, silent failure mode; a
fallback chain plus the hard "recognised nothing -> raise" guard in
`cimenta2.discover()` turns that into either a recovery or a loud error.
"""

from __future__ import annotations

import re
from urllib.parse import unquote, urlsplit

from etl.connectors.extraction import first_present

# Live-verified 2026-08-04 against the complete sitemap: all 3,917 asset
# URLs match this exact shape, 3,917 distinct 18-character Salesforce record
# ids paired 1:1 with 3,917 distinct reference codes (zero duplicates on
# either side). The id length is accepted as 15-18 because Salesforce ids
# are natively 15 characters case-sensitive and 18 characters
# case-insensitive; the sitemap publishes the 18-character form today, and
# pinning the parser to 18 alone would break on a generator that switched to
# the equally valid 15-character form.
_ASSET_PATH_RE = re.compile(
    r"^/inmuebles/s/ga-activo/(?P<record_id>[A-Za-z0-9]{15,18})/(?P<reference>[^/]+)$"
)

# Deliberately tolerant sibling of the above, used only as a fallback: same
# path prefix, but indifferent to a trailing slash, a query string, a
# fragment, or extra path noise after the reference. See
# `reference_code_from_url` for why that laxness is wanted in second
# position and not in first.
_ASSET_PATH_LOOSE_RE = re.compile(
    r"/inmuebles/s/ga-activo/(?P<record_id>[A-Za-z0-9]{15,18})/(?P<reference>[^/?#]+)"
)

_LOC_RE = re.compile(r"<loc>\s*([^<\s]+)\s*</loc>", re.IGNORECASE)

# The asset object's child sitemap, as named in the live sitemap index.
# `-1` is the numbered partition; `-weekly` is a second entry the index also
# publishes. Live-verified 2026-08-04: the two are not a full set and a
# delta -- they returned byte-identical 556,639-byte bodies with the same
# 3,917 URLs, so either one alone is the complete asset catalogue. That is
# what makes the weekly variant a safe fallback rather than a partial one.
_ASSET_SITEMAP_TOKEN = "sitemap-ga_activo__c-1.xml"
_ASSET_SITEMAP_WEEKLY_TOKEN = "sitemap-ga_activo__c-weekly.xml"


def iter_locs(xml: str) -> list[str]:
    """Every `<loc>` value in a sitemap or sitemap index, in document order.

    A regex rather than an XML parser, matching the house pattern
    (`vivantial.py`, `servihabitat.py`): these documents are machine-
    generated by Salesforce and the connector wants a *lenient* read, since
    the realistic failure mode is an HTML error page served with a 200,
    which a strict parser would turn into an XML exception rather than the
    "zero entries" signal `cimenta2.discover()` checks for explicitly.
    """
    return _LOC_RE.findall(xml)


def record_id_from_url(url: str) -> str | None:
    """The 18-character Salesforce record id, used as this connector's
    `external_id`.

    The record id is the external_id rather than the human reference code
    because it is what the URL is *addressed* by: the reference code is a
    Cajamar-side business identifier that a servicer is free to re-issue,
    while the record id is the primary key of the row the page renders.
    Using the reference code would also silently collapse two assets the day
    Cajamar reuses one, and `listing` is keyed `UNIQUE (source,
    external_id)`.
    """
    path = urlsplit(url).path
    strict = _ASSET_PATH_RE.match(path)
    if strict is not None:
        return strict.group("record_id")
    loose = _ASSET_PATH_LOOSE_RE.search(path)
    if loose is not None:
        return loose.group("record_id")
    return None


def reference_code_from_url(url: str) -> str | None:
    """The per-property reference code Cajamar puts in the URL slug (#72).

    Two getters, in decreasing strictness:

    1. The exact shape every one of the 3,917 live asset URLs has today.
    2. A tolerant re-read that ignores a trailing slash, a query string, a
       fragment, or trailing path noise.

    The second is not defensive boilerplate. This connector's *only*
    per-property datum is this code, and a sitemap generator appending
    `?utm_source=...` or a trailing `/` is a cosmetic change a site can make
    at any time without notice. With a strict-only parse that change would
    make every URL unrecognisable at once, which for a
    `discovers_full_inventory = True` connector reads as a total withdrawal
    of the catalogue rather than as the parsing regression it is.

    Percent-decoded because the sibling `inv-expediente` sitemap does emit
    percent-encoded UTF-8 in its slugs (`...canj%C3%A1yar-almer%C3%ADa`);
    no live asset reference needs decoding today, but decoding an
    already-plain ASCII code is a no-op, and not decoding a future accented
    one would store a mangled value.
    """
    path = urlsplit(url).path

    def strict() -> str | None:
        match = _ASSET_PATH_RE.match(path)
        return unquote(match.group("reference")) if match else None

    def loose() -> str | None:
        match = _ASSET_PATH_LOOSE_RE.search(path)
        return unquote(match.group("reference")) if match else None

    code = first_present(strict, loose, field="cimenta2.reference_code")
    if code is None:
        return None
    code = code.strip()
    return code or None


def parse_asset_url(url: str) -> tuple[str, str] | None:
    """`(record_id, reference_code)` for an asset URL, or None if it is not one.

    Returning None (rather than raising) for a non-asset URL is what lets
    `discover()` walk a mixed sitemap and simply ignore anything that is not
    a `ga-activo` entry. The "we recognised *nothing*" case is the one that
    raises, and that check lives in `discover()` where the count is known.
    """
    record_id = record_id_from_url(url)
    if record_id is None:
        return None
    reference = reference_code_from_url(url)
    if reference is None or reference == record_id:
        # A slug-less URL (`/ga-activo/<id>`) would otherwise hand back the
        # record id as though it were a Cajamar reference code, seeding the
        # dedup engine's reference_code signal with a value that is not a
        # reference code at all. No such URL exists in the live sitemap;
        # this is the honest handling if one ever appears.
        return None
    return record_id, reference


def asset_sitemap_url(index_xml: str, *, base_url: str, default_url: str) -> str | None:
    """Pick the asset child-sitemap URL out of the sitemap index.

    Three getters, and the middle one is the interesting one:

    1. The numbered partition (`...ga_activo__c-1.xml`) the index advertises.
    2. The `-weekly` variant. Safe as a fallback specifically because it was
       live-verified to be the *same complete set*, not a recent-changes
       delta -- see `_ASSET_SITEMAP_WEEKLY_TOKEN`. A guessed-at "weekly
       means delta" would have been a quietly partial sweep, which is the
       one thing a full-inventory connector must not do.
    3. The well-known URL, constructed directly. Covers an index that
       returns successfully but lists nothing recognisable.

    Returns None only when the index itself was unreadable enough that even
    `default_url` should not be trusted -- the caller decides what to do.
    """
    locs = iter_locs(index_xml)

    def numbered() -> str | None:
        return next((loc for loc in locs if _ASSET_SITEMAP_TOKEN in loc), None)

    def weekly() -> str | None:
        return next((loc for loc in locs if _ASSET_SITEMAP_WEEKLY_TOKEN in loc), None)

    def well_known() -> str | None:
        return default_url

    url = first_present(numbered, weekly, well_known, field="cimenta2.asset_sitemap")
    if url is None:
        return None
    if url.startswith("/"):
        return f"{base_url.rstrip('/')}{url}"
    return url
